AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambda NodeJS starter project
Parameters:
LambdaName:
    Description: "Name for this function"
    Type: "String"
LambdaDescription:
    Description: "Description for this function"
    Type: "String"
LambdaRole:
    Description: "Role for this function" 
    Type: "String"
Resources:
LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: S3 Object Custom Resource
      Handler: lambda_function.lambda_handler
      Role: arn:aws:iam::482781774333:role/service-role/index-photos-role-4u13jryo
      FunctionName: s3_trigger_lambda3
      Layers: 
       - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-python38-elasticsearch:4
      Code:
        S3Bucket: voicecontrolledsearchb2
        S3Key: code_pipeline.zip
      Timeout: 60
      Runtime: python3.8
